// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20241017191830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("productId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            IsActive = true,
                            Price = 40000m,
                            productName = "IPhone 14"
                        },
                        new
                        {
                            productId = 2,
                            IsActive = false,
                            Price = 50000m,
                            productName = "IPhone 15"
                        },
                        new
                        {
                            productId = 3,
                            IsActive = true,
                            Price = 60000m,
                            productName = "IPhone 16"
                        },
                        new
                        {
                            productId = 4,
                            IsActive = false,
                            Price = 70000m,
                            productName = "IPhone 17"
                        },
                        new
                        {
                            productId = 5,
                            IsActive = true,
                            Price = 80000m,
                            productName = "IPhone 18"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
